kind: BuildConfig
apiVersion: v1
metadata:
  labels:
    name: contra-sample-pipeline-vm
  name: contra-sample-pipeline-vm
spec:
  source:
    type: Git
    git:
      uri: https://github.com/CentOS-PaaS-SIG/contra-env-sample-project.git
      ref: master
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: config/pipelines/contra-sample-pipeline-vm/Jenkinsfile