---
- hosts: '{{ hosts | default("all") }}'
  become: '{{ become | default("no") }}'
  become_user: '{{ become_user | default("root") }}'
  remote_user: '{{ user | default("root") }}'
  tasks:
      - set_fact:
          real_ansible_host: "{{ ansible_host | default(inventory_hostname) }}"

      - name: 01 hostname check
        command: hostname